### ISSUE TITLE
correct jsconfco comment about profitability

### ISSUE THREAD

**Issue by buritica** [kosamari/who-pays-tech-speakers#25]
[this entry](http://whopays.techspeakers.info/563115c113e791d924f3b966) this entrymentions jsconfco as a `for profit` event

jsconfco is a publicly, not-for-profit, community organized event https://medium.com/colombia-dev/how-we-re-changing-colombia-through-open-source-communities-and-why-we-need-your-help-7825a9fd020e

thanks

**Comment by kosamari** [comment]
Thanks @buritica I need to create new field in DB for "edit" section and change how FE gets rendered. Will work on it tonight.

**Comment by kosamari** [comment]
This report was changed from "for profit" to "not for profit"
http://whopays.techspeakers.info/563115c113e791d924f3b966
Thanks for info @buritica !

---

Because of anonymous nature the form, I've kept indication that post was edited by admin & added link to this issue for reference.

![who_pays_conference_speakers_ 3](https://cloud.githubusercontent.com/assets/4581495/10839229/a0a0636c-7ea7-11e5-9a3c-7cb135afc93f.png)
![who_pays_speakers_ 3](https://cloud.githubusercontent.com/assets/4581495/10839232/abb66b98-7ea7-11e5-9df3-866c43ae95d6.png)
